### ISSUE TITLE
!setup or /setup not working

### ISSUE THREAD

**Issue by tjmorin327** [aaronrai24/DollarDiscordBot#8]
Dependencies are not being set up automatically

**Comment by aaronrai24** [comment]
Updated to add /setup back, first checks to verify if voice/text channel exists if it does we throw a warning otherwise we create the channel, screenshots of logs confirming workflow, tested with no channels existing, one channel exists, and both channels existing

Both channels already exist:
![image](https://github.com/aaronrai24/DollarDiscordBot/assets/55159220/1297ce19-dba8-4833-9797-9c4ad2db6cab)

One channel exists:
![image](https://github.com/aaronrai24/DollarDiscordBot/assets/55159220/5b94a5f6-95bf-4bf1-b20a-c2e5ad86c426)

No channels exist:
![image](https://github.com/aaronrai24/DollarDiscordBot/assets/55159220/691b0ce1-7f08-4cd7-b04c-6511832a0299)
